/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rasystem;

/**
 *
 * @author Dell
 */
public class ManHP extends javax.swing.JFrame {

    /**
     * Creates new form ManHP
     */
    public ManHP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backB = new javax.swing.JButton();
        dispMenuB = new javax.swing.JButton();
        updMenuB = new javax.swing.JButton();
        orderB = new javax.swing.JButton();
        salesB = new javax.swing.JButton();
        invB = new javax.swing.JButton();
        changeB = new javax.swing.JButton();
        addinvB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME !!");

        backB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backB.setText("<< LOGOUT");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });

        dispMenuB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dispMenuB.setText("DISPLAY MENU");
        dispMenuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispMenuBActionPerformed(evt);
            }
        });

        updMenuB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        updMenuB.setText("UPDATE MENU");
        updMenuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updMenuBActionPerformed(evt);
            }
        });

        orderB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        orderB.setText("TAKE ORDER");
        orderB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBActionPerformed(evt);
            }
        });

        salesB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        salesB.setText("SALES RECORDS");
        salesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesBActionPerformed(evt);
            }
        });

        invB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        invB.setText("MANAGE INVENTORY");
        invB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invBActionPerformed(evt);
            }
        });

        changeB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        changeB.setText("CHANGE PASSWORD");
        changeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBActionPerformed(evt);
            }
        });

        addinvB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addinvB.setText("ADD TO INVENTORY");
        addinvB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addinvBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dispMenuB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(updMenuB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backB)
                            .addComponent(invB, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(salesB, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addinvB, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dispMenuB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updMenuB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addinvB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        
        Open1 x = new Open1();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        this.dispose() ;
        
    }//GEN-LAST:event_backBActionPerformed

    private void dispMenuBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispMenuBActionPerformed
       
        DispMenus x = new DispMenus();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        this.dispose() ;
        
    }//GEN-LAST:event_dispMenuBActionPerformed

    private void updMenuBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updMenuBActionPerformed
         
         UpdateMenu x=new UpdateMenu();
         x.setVisible(true);        
         x.setLocationRelativeTo(null);        
         this.dispose() ;  
         
    }//GEN-LAST:event_updMenuBActionPerformed

    private void orderBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBActionPerformed
       
        DispMenus x = new DispMenus();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        this.dispose() ;
        
    }//GEN-LAST:event_orderBActionPerformed

    private void salesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesBActionPerformed
       
        SalesRecord x = new SalesRecord();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        this.dispose() ;
        
    }//GEN-LAST:event_salesBActionPerformed

    private void invBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invBActionPerformed
       
        Inventory x=new Inventory();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        this.dispose() ;
        
    }//GEN-LAST:event_invBActionPerformed

    private void changeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBActionPerformed
        
        ChangePassword x = new ChangePassword();
        x.setVisible(true);        
        x.setLocationRelativeTo(null);
        this.dispose();  
        
    }//GEN-LAST:event_changeBActionPerformed

    private void addinvBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addinvBActionPerformed
        
        AddIng x=new AddIng();
        
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        this.dispose() ;
        
    }//GEN-LAST:event_addinvBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addinvB;
    private javax.swing.JButton backB;
    private javax.swing.JButton changeB;
    private javax.swing.JButton dispMenuB;
    private javax.swing.JButton invB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton orderB;
    private javax.swing.JButton salesB;
    private javax.swing.JButton updMenuB;
    // End of variables declaration//GEN-END:variables
}
