/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rasystem;

/**
 *
 * @author Dell
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class RemoveItem extends javax.swing.JFrame {

    /**
     * Creates new form RemoveItem
     */
    private int RES;   
    
    public RemoveItem() {
        
        initComponents();
        RES = 0 ;
        remove.setVisible(false) ; 
        details.setVisible(false) ; 
        
    }
     
    public int getflag() {
        return RES;
    }

    public void click1() {
        getActionPerformed(null);
    }
    
    public void setDetails( String iid ) {       
        id.setText(iid);          
        RES = 0;
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        get = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        details = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Item ID No :");

        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setText("<< BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        remove.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        remove.setText("REMOVE");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        get.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        get.setText("GET DETAILS");
        get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getActionPerformed(evt);
            }
        });

        details.setColumns(20);
        details.setRows(5);
        jScrollPane2.setViewportView(details);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(get, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(remove))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(get)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remove)
                    .addComponent(back))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        UpdateMenu x = new UpdateMenu();
        x.setVisible(true);
        x.setLocationRelativeTo(null);
        this.dispose() ;

    }//GEN-LAST:event_backActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
       
            try
            {
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/RAS","root","go5a1on1");
                Statement st = con.createStatement();
                
                String query2 = "delete from Dish where ID = \"" + id.getText() +  "\"; ";
                st.executeUpdate(query2) ;
                JOptionPane.showMessageDialog(null,"ITEM REMOVED SUCCESSFULLY !! ","Update",JOptionPane.INFORMATION_MESSAGE);
                       
                RemoveItem x=new RemoveItem();
                x.setVisible(true);        
                x.setLocationRelativeTo(null);                 
                this.dispose() ;      
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null,ex,"Alert",JOptionPane.ERROR_MESSAGE);                 
            }
        
        
    }//GEN-LAST:event_removeActionPerformed

    private void getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getActionPerformed
         
        if ( (id.getText()).equals("") == false )
        {   
            details.setText("") ; 
            try
            {
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/RAS","root","go5a1on1");
                Statement st = con.createStatement();

                String query1 = "Select * from DISH where ID = \"" + id.getText() +  "\"; ";
                ResultSet rs=st.executeQuery(query1);
               
                if ( !rs.isBeforeFirst() )
                {
                    JOptionPane.showMessageDialog(null,"ITEM with this ID ABSENT !! ","Remove Failed",JOptionPane.ERROR_MESSAGE);
                    id.setText(null);
                }
                else
                {   
                    rs.next() ; 
                    remove.setVisible(true) ; details.setVisible(true) ; 
                    RES = 1 ; 
                    
                    String name1 = (rs.getString("name")) ; String cuisine1 = (rs.getString("cuisine")) ; 
                    
                    String SP =(""+rs.getInt("sp")+"") ; String MP = (""+rs.getInt("mp")+"") ;                     
                    String Ing1 = (rs.getString("I1")) ; String Q1 = (""+rs.getInt("Q1")+"") ;                     
                    String Ing2 = (rs.getString("I2")) ; String Q2 = (""+rs.getInt("Q2")+"") ;                      
                    String Ing3 = (rs.getString("I3")) ; String Q3 = (""+rs.getInt("Q3")+"") ;                     
                    String Ing4 = (rs.getString("I4")) ; String Q4 = (""+rs.getInt("Q4")+"") ;                       
                    
                    details.append("******************************\n") ;
                    details.append(name1.toUpperCase()+"\n") ;
                    details.append(cuisine1.toUpperCase()+"\n") ;
                    
                    details.append("Selling Price : " + SP + "\n") ;
                    details.append("Making Price  : " + MP + "\n") ;
                    
                    details.append(Ing1.toUpperCase() + " -> " + Q1 + " units\n") ;
                    details.append(Ing2.toUpperCase() + " -> " + Q2 + " units\n") ;
                    details.append(Ing3.toUpperCase() + " -> " + Q3 + " units\n") ;
                    details.append(Ing4.toUpperCase() + " -> " + Q4 + " units\n") ;
                    
                    details.append("******************************") ;
                }
            }
            catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null,ex,"Alert",JOptionPane.ERROR_MESSAGE);                 
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "ENTER ID !! ","Alert",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_getActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextArea details;
    private javax.swing.JButton get;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton remove;
    // End of variables declaration//GEN-END:variables
}
